// generated by ai

import type { TextAlignment } from '../types'

/**
 * 获取 Flex 布局的文本对齐方向
 */
function getFlexAlignment(style: CSSStyleDeclaration): TextAlignment {
  const flexDirection = style.flexDirection
  const isHorizontal = flexDirection === 'row' || flexDirection === 'row-reverse'

  if (isHorizontal) {
    // 主轴水平：justifyContent 控制水平对齐
    const justifyContent = style.justifyContent
    if (justifyContent === 'center')
      return 'center'
    if (justifyContent === 'flex-end' || justifyContent === 'end')
      return 'right'
    return 'left'
  }

  // 主轴垂直：alignItems 控制水平对齐
  const alignItems = style.alignItems
  if (alignItems === 'center')
    return 'center'
  if (alignItems === 'flex-end' || alignItems === 'end')
    return 'right'
  return 'left'
}

/**
 * 获取 Grid 布局的文本对齐方向
 */
function getGridAlignment(style: CSSStyleDeclaration): TextAlignment {
  const justifyItems = style.justifyItems
  if (justifyItems === 'center')
    return 'center'
  if (justifyItems === 'end')
    return 'right'
  return 'left'
}

/**
 * 获取普通流布局的文本对齐方向
 */
function getTextAlignAlignment(style: CSSStyleDeclaration): TextAlignment {
  const textAlign = style.textAlign
  const direction = style.direction

  // 处理逻辑值 start/end
  if (textAlign === 'start') {
    return direction === 'rtl' ? 'right' : 'left'
  }
  if (textAlign === 'end') {
    return direction === 'rtl' ? 'left' : 'right'
  }

  // 处理直接值
  if (textAlign === 'center')
    return 'center'
  if (textAlign === 'right')
    return 'right'
  if (textAlign === 'justify')
    return 'left' // 两端对齐视为左对齐

  return 'left'
}

/**
 * 获取元素的文本对齐方向
 *
 * 判断优先级：
 * 1. Flex 布局：根据 flex-direction 判断使用 justify-content 或 align-items
 * 2. Grid 布局：使用 justify-items
 * 3. 普通流布局：使用 text-align（需处理 start/end 逻辑值）
 *
 * @param element - HTML 元素
 * @returns 文本对齐方向：'left' | 'center' | 'right'
 */
export function getTextAlignment(element: Element): TextAlignment {
  const computedStyle = window.getComputedStyle(element)
  const display = computedStyle.display

  // 场景1: Flex 布局
  if (display === 'flex' || display === 'inline-flex') {
    return getFlexAlignment(computedStyle)
  }

  // 场景2: Grid 布局
  if (display === 'grid' || display === 'inline-grid') {
    return getGridAlignment(computedStyle)
  }

  // 场景3: 普通流布局（包括 block, inline-block 等）
  return getTextAlignAlignment(computedStyle)
}
