// generated by ai
/**
 * 获取外部CSS文件内容
 */
export async function fetchCSSContent(url: string): Promise<string> {
  try {
    const response = await fetch(url)

    if (!response.ok) {
      throw new Error(`获取CSS失败: ${response.status} ${response.statusText}`)
    }

    const cssText = await response.text()

    if (!cssText.trim()) {
      throw new Error('CSS内容为空')
    }

    return cssText
  }
  catch (error) {
    const message = error instanceof Error ? error.message : '未知错误'
    throw new Error(`获取CSS失败 [${url}]: ${message}`)
  }
}

// generated by ai
/**
 * 批量获取多个CSS文件内容
 */
export async function fetchMultipleCSSContents(
  urls: string[],
): Promise<Map<string, string>> {
  const results = new Map<string, string>()

  const promises = urls.map(async (url) => {
    try {
      const content = await fetchCSSContent(url)
      results.set(url, content)
    }
    catch (error) {
      console.error(`获取CSS失败: ${url}`, error)
      results.set(url, '')
    }
  })

  await Promise.all(promises)

  return results
}
