// generated by ai
export interface StyleSheetInfo {
  href: string | null
  cssText: string
  rules: CSSRuleInfo[]
}

// generated by ai
export interface CSSRuleInfo {
  selectorText: string
  cssText: string
  properties: Record<string, string>
}

// generated by ai
export interface DOMStyleInfo {
  inlineStyles: StyleSheetInfo[]
  externalStyles: StyleSheetInfo[]
  allRules: CSSRuleInfo[]
}
